version: "3.8"

services:
  frontend:
    image: muthu42doc/frontend:latest
    container_name: frontend
    ports:
      - "82:80"
    depends_on:
      - backend

  backend:
    image: muthu42doc/backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
    volumes:
      - /var/log/myapp:/var/log/myapp

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: employee_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
